#' @title Sample Data for Small Area Estimation using Hierarchical Bayesian Method for Rao Yu Model under Beta Distribution when \code{rho = 0}
#'
#' @description Dataset to simulate Small Area Estimation using Hierarchical Bayesian Method for Rao-Yu Model under Beta Distribution with rho = 0
#' This data is generated by these following steps:
#' \enumerate{
#' \item Generate random effect area \code{v}, random effect for area i at time point j \code{u}, epsilon \eqn{$\epsilon$}, variance of ydi \code{vardir}, sampling error \code{e}, auxiliary \code{xdi1} and \code{xdi2}
#' \itemize{
#' \item Set coefficient \eqn{$\beta_{0}=\beta_{1}=\beta_{2}=2$} and \eqn{$\rho = -0,5$}
#' \item Generate random effect area \code{v_{i}~N(0,1)}
#' \item Generate auxiliary variable \code{xdi1_{ij}~U(1,2)}
#' \item Generate auxiliary variable \code{xdi2_{ij}~U(1,3)}
#' \item Generate epsilon \eqn{$\epsilon_{ij}}\code{~N(0,1)$}
#' \item Generate \eqn{$\phi\code{~Gamma(1,0.5)$}
#' \item Calculate \eqn{$\mu_{ij}=exp(\beta_{0}+\beta_{1}xdi1_{ij}+\beta_{2}xdi2_{ij}+v_{i}+\epsilon_{ij})/(1+\beta_{0}+\beta_{1}xdi1_{ij}+\beta_{2}xdi2_{ij}+v_{i}+\epsilon_{ij})$}
#' \item Calculate \eqn{$\A_{ij}=\mu_{ij}*\phi$}
#' \item Calculate \eqn{$\B_{ij}=(1-\mu_{ij})*\phi$}
#' \item Generate direct estimation\code{ydi_{ij}~Beta(A_{ij},B_{ij})}
#' \item Calculate variance of ydi with \code{vardir_{ij}={A_{ij}*B_{ij}}/((A_{ij}+B_{ij})^2(A_{ij}+B_{i,j}+1))}
#' \item Set \code{area=20} and \code{period=5}
#' }
#' }
#' \item Auxiliary variables \code{xdi1,xdi2}, direct estimation \code{y}, \code{area}, \code{period}, and \code{vardir} are combined in a dataframe called \code{dataPanelbeta}
#' }
#'
#' @format A data frame with 100 rows and 6 variables::
#' \describe{
#' \itemize{
#'   \item{ydi}{Direct Estimation of y}
#'   \item{area}{Area (domain) of the data}
#'   \item{period}{Period (subdomain) of the data}
#'   \item{vardir}{Sampling Variance of y}
#'   \item{xdi1}{Auxiliary variable of xdi1}
#'   \item{xdi2}{Auxiliary variable of xdi2}
#'   }
#' }
#'
#'
"dataPanelbeta"
